### ISSUE TITLE
SoftAdapt still required by ACTIVA.py, but unavailable

### ISSUE THREAD

**Issue by KOD1S** [SindiLab/ACTIVA#12]
Hi @dr-aheydari, thanks for your quick response, however the ACTIVA.py file still calls for SoftAdapt, which is not available.

![image](https://user-images.githubusercontent.com/63750985/194303538-1d1a5a4e-0a23-4730-a994-7bc81f0e7e33.png)

**Comment by KOD1S** [comment]
I have also found it necessary to make sure protobuf 3.20 or earlier is installed for the program to run.

**Comment by dr-aheydari** [comment]
Hi @KOD1S!

Thank you for catching that! I have now removed all SoftAdapt-related code from main (`ACTIVA.py`). 

I am not sure about the dependency on `protobuf 3.20`; please let me do some testing with that on my end. I will update the requirements to reflect any changes I may need to do.

Thank you again very much for catching the bug in the main! Please let me know if any other issue pops up!
