### ISSUE TITLE
About AUC and MMD values

### ISSUE THREAD

**Issue by kingkingofall** [SindiLab/ACTIVA#13]
Hi, ACTIVA is very uesful for my research. But I ran into trouble in the process, do you still have the code to test the model AUC and MMD values? thanks very much!

**Comment by dr-aheydari** [comment]
hi @kingkingofall,

This issue completely fell off of my radar, my sincerest apologies. 

For MMD, we used the [shogun package](https://github.com/shogun-toolbox/shogun) following the tutorials. We calculated the AUC using standard [sklearn function](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.auc.html) : )

Again my apologies for being late, and I hope this helps despite being months late!
