### ISSUE TITLE
S3 Download Issue

### ISSUE THREAD

**Issue by marvinli00** [SindiLab/ACTIVA#14]
Hi,

Thanks for the amazing paper.
I'm studying how the code is structured and worked.
For downloading the preprocessed data, do you know how I download file from s3:// url?

Best regards,
Marvin

**Comment by dr-aheydari** [comment]
Hi @marvinli00,

My sincere apologies for the late response (Sorry, I don't know why my response was not posted here when I replied to the email couple of weeks ago). 

To download the processed data (or any of the S3 files), you can use AWS command Line (CLI) as described [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/download-objects.html). Essentially, once you have AWS CLI on your machine, you can run:

```
$ aws s3 cp <URI WHERE THE FILE IS STORED> <PATH TO WHERE YOU WANT TO SAVE ON YOUR MACHINE>
```

Alternatively, if you don't want to deal with the AWS CLI, you can also download our files from [Zenodo](https://zenodo.org/record/5879639#.ZDmiQr3MKUc). 

I will close this issue for now, but please let me know if anything else comes up or if you have any other questions!

**Comment by marvinli00** [comment]
Hi @dr-aheydari,

Thanks for your reply, and I really appreciated it. Following your suggestion with aws s3 cp command, I have downloaded the preprocessed files successfully, but I encountered "fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden" for all post processed files. Do you know if those files are publicly accessible?

Sincerely,
Marvin
