### ISSUE TITLE
A bug in L376-377 in ACTIVA.py

### ISSUE THREAD

**Issue by zhuj423** [SindiLab/ACTIVA#2]
It looks a bug in L376-377 in ACTIVA.py, https://github.com/odavalos/ACTIVA/blob/main/ACTIVA.py#L376, which should be
```
rec_mu, rec_logvar = model.encode(rec.detach()) 
fake_mu, fake_logvar = model.encode(fake.detach())
```
I'm interested in any change of performance after correcting this bug and also how does it compare to regular VAE.
Thanks a lot!

**Comment by dr-aheydari** [comment]
Hi @zhu-j,

Sorry I just saw this. You are absolutely correct! this was fixed on our AWS machine but was never pushed to my local/GitHub that was sent here. I will fix this in the code here shortly.
