### ISSUE TITLE
Python version issue

### ISSUE THREAD

**Issue by MajorIsato** [SindiLab/ACTIVA#3]
Hello, I started following your work "ACTIVA" couple of days ago, it's very impressive and inspirational : ), I'm trying to implement this model right now and I wonder what version of python were you using when ACTIVA were being built? It will be super helpful, thank you guys!

**Comment by odavalos** [comment]
Hello! Any version >= Python 3.6 should work fine!

**Comment by MajorIsato** [comment]
Okay! Thank you for your response!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SindiLab/ACTIVA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月19日(星期四) 凌晨2:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SindiLab/ACTIVA] Python version issue (#3)





 
Hello! Any version &gt;= Python 3.6 should work fine!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dr-aheydari** [comment]
Closing this issue now as it seems resolved. @MajorIsato Please feel free to reopen (or open a new one) if there are any issues!
