### ISSUE TITLE
Versions of some packages conflict with what ACTINN depends on

### ISSUE THREAD

**Issue by duohongrui** [SindiLab/ACTIVA#4]
Hi, ACTIVA is an ideal tool for me to simulate scRNA-seq data where real data can be modelled. However, when I installed the packages listed in requirements.txt under Ubuntu18.04 with python 3.8.10, the error occurred.

```
ERROR: Cannot install -r requirements.txt (line 7) and torch==1.5.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==1.5.1
    actinn 0.0.2 depends on torch==1.9.1
```
```
ERROR: Cannot install -r requirements.txt (line 7) and scanpy==1.6.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested scanpy==1.6.0
    actinn 0.0.2 depends on scanpy==1.7.0
```
It seems like that the versions of **scanpy** and **torch** listed in requirements.txt conflict with what ACTINN depends on. Could you check the compatibility between them? 
Thanks very much!

**Comment by dr-aheydari** [comment]
Hi @duohongrui,

Sorry for the late reply; for some reason, I did not get a notification for this issue (I should check my settings).  

I have fixed the dependency issue in both `setup.py` and `requirements.txt` (found in [this commit](https://github.com/SindiLab/ACTIVA/commit/5f6b12db3a87aaba7caf2c7eac7e24ad3276be80)). I tested the package (installed and ran an example code) and things seemed fine on my end, so hopefully the issue will be fixed on your end too after you refresh your clone of the repo.

One last comment: If you are using A100 GPU(s), then the torch version that you need to install will be different (I have added a note about this in `requirements.txt`). In that case, you can install the specific torch binaries that are compatible with A100s, and ACTIVA or ACTINN will run just fine (I have tested our code on A100s as well).

Hope this helped. I will close the issue but feel free to open it again if anything goes wrong :)
