### ISSUE TITLE
Link to File Download

### ISSUE THREAD

**Issue by CenXiang** [SindiLab/ACTIVA#5]
It is very difficult or even impossible for Chinese users to download the Pre- and Post- processed Data or other models in S3 URI link. Could you please find another way to obtain them? I'd appreciate it, if that's possible. Thanks!

**Comment by dr-aheydari** [comment]
Hi @CenturyAI,

Sorry to hear about the difficulties of downloading our data hosted on AWS from China. We do host our data on Zenodo as well, which can be found [here](https://zenodo.org/record/5842658#.YlyJrJLMIUE) (same link as in our paper). I hope downloading our data from Zenodo is a bit easier for you : )

Feel free to let me know if there are any other issues with data download.

Best,
Ali

**Comment by ShijiXiang1999** [comment]
> Hi @CenturyAI,
> 
> Sorry to hear about the difficulties of downloading our data hosted on AWS from China. We do host our data on Zenodo as well, which can be found [here](https://zenodo.org/record/5842658#.YlyJrJLMIUE) (same link as in our paper). I hope downloading our data from Zenodo is a bit easier for you : )
> 
> Feel free to let me know if there are any other issues with data download.
> 
> Best, Ali

Thank you very much for your reply!
