### ISSUE TITLE
Generating specific cell types

### ISSUE THREAD

**Issue by KOD1S** [SindiLab/ACTIVA#7]
Hi,

Is there a tutorial posted anywhere relating to the generation of specific cell types from ACTIVA?

We have implemented the ACTINN classifier after the fact to choose cells above a classification confidence level but in your paper it sounds as is this function is integrated into the model. Is this the case? If so how would we use it?

Many thanks,

Richard

**Comment by dr-aheydari** [comment]
Hi @KOD1S,

The method you have been using makes perfect sense and should give you the cells you are looking for (up to the desired confidence level). Our approach depends on the classifier conditioner as well, so you are on the right track!

Please let me know if you'd like to discuss this in more detail

**Comment by KOD1S** [comment]
Hi @dr-aheydari 

Thanks very much for your reply. Could you tell me the confidence threshold that you used for you results in your paper?

Many thanks,

Richard

**Comment by KOD1S** [comment]
Hi @dr-aheydari 

Do you have any more info on the mentioned confidence threshold you used to attain the results in your paper? I am attempting to recreate your results and feel that this is an important step.

Kind regards,

Richard

**Comment by KOD1S** [comment]
Hi @dr-aheydari  I would also like to know whether the pretrained models available for download are fully trained networks capable of producing realistic cell data, or if they are pre-trained in relation to needing further training?

Many thanks,

Richard

**Comment by dr-aheydari** [comment]
@KOD1S

Hi Richard!

Thank you for your great questions! Here are the answers:

(1) We chose cells that the model was over 90% confident about. 

(2) Could you please open a new issue regarding the pre-trained models? I apologize if this sounds nit-picky, but I want to ensure that the issue titles (in this case, "Generating specific cell types") and the topics discussed in each thread fall under the same umbrella. However, the quick answer to your question is: _Yes, depending on your use case and data_. I'd be happy to elaborate more on the new issue you will be opening : ) 

I will close this issue now, but please feel free to reopen issue for any additional questions on generating specific cell types : )

Thank you again very much for your interest and contributing to the package through your great questions! 

Ali

**Comment by KOD1S** [comment]
Hi @dr-aheydari , thank you for the feedback on this, it's much appreciated. While using the package I have encountered some issues which prevent me from using this any more. I've created two issues as I believe they are separate. We are very keen to test this method and are looking to recreate the results from your paper.

**Comment by dr-aheydari** [comment]
Hi Richard (@KOD1S),

Thank you so much for your interest and for actively improving our package through opening great issues. I'd be happy to also have a quick chat to answer any questions you may have on the algorithm or any of the methods we used. 

Please don't hesitate to shoot me an email (aliheydari [at] ucdavis [dot] edu) if you'd like to set up some time to chat about ACTIVA!
