### ISSUE TITLE
Access to Post-Processed Data

### ISSUE THREAD

**Issue by KOD1S** [SindiLab/ACTIVA#9]
Hi,

I am receiving the following error when trying to access the Post-Processed Data through the CLI, would it be possible to access it some other way?

![image](https://user-images.githubusercontent.com/63750985/188863810-216d821c-aefb-4214-8a75-6b0f7239676b.png)

Cheers,

Richard

**Comment by dr-aheydari** [comment]
Hi @KOD1S ,

Thanks for your question. As described in [this issue](https://github.com/SindiLab/ACTIVA/issues/6#issuecomment-1173016484), you can not use `wget` to download data from AWS S3. In general, once you have the AWS CLI and an object's URI, one can download a file using the following:

```bash
$aws s3 cp <S3 URI> <Location and name of where the download should go to>
```
Please refer to [this guide](https://acloudguru.com/blog/engineering/aws-s3-cheat-sheet) for more information on how to use S3 CLI.

I hope this helps!

Best,
Ali
